# Generated by Django 4.2.30 on 2026-08-18 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('slot_time', models.CharField(default='05:30 AM - 07:00 AM', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Scheduled (Pending)'), ('DELIVERED', 'Delivered at Doorstep'), ('SKIPPED', 'Skipped / Paused')], default='PENDING', max_length=20)),
                ('proof_image_url', models.URLField(blank=True, default='')),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deliveries', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['delivery_date', 'id'],
            },
        ),
    ]
