# Generated by Django 4.2.30 on 2026-08-18 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub_code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('latitude', models.FloatField(default=17.432)),
                ('longitude', models.FloatField(default=78.407)),
                ('manager_name', models.CharField(max_length=100)),
                ('manager_phone', models.CharField(max_length=20)),
                ('fssai_license', models.CharField(default='13621014000342', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(default='Hyderabad', max_length=100)),
                ('pincodes', models.CharField(help_text='Comma-separated pincodes, e.g., 500033, 500096', max_length=255)),
                ('radius_km', models.FloatField(default=5.0)),
                ('latitude', models.FloatField(default=17.432)),
                ('longitude', models.FloatField(default=78.407)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active & Delivering'), ('EXPANDING', 'Expanding Soon'), ('WAITLIST', 'Waitlist Only')], default='ACTIVE', max_length=20)),
                ('active_households', models.PositiveIntegerField(default=128)),
                ('popular_societies', models.TextField(default='My Home Bhooja, Rainbow Vistas, Aparna Sarovar, Lodha Bellezza')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to='deliveries.locationhub')),
            ],
        ),
    ]
