# Generated by Django 4.2.30 on 2026-08-19 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_populate_initial_service_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='deliveries.locationhub'),
        ),
    ]
