# Generated by Django 4.2.30 on 2026-08-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0004_deliverytask_hub'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationhub',
            name='coverage_radius_km',
            field=models.FloatField(default=5.0),
        ),
    ]
