# Generated by Django 4.2.30 on 2026-08-19 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_alter_product_category_product_category_ref'),
        ('subscriptions', '0002_subscription_hub'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deliveries', '0005_locationhub_coverage_radius_km'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveOrder',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('order_type', models.CharField(choices=[('ONE_TIME', 'One-Time Order'), ('EXPRESS', 'Express Delivery'), ('SUBSCRIPTION_ORDER', 'Subscription Batch Order')], default='ONE_TIME', max_length=30)),
                ('status', models.CharField(choices=[('PLACED', 'Order Placed'), ('PREPARING', 'Preparing / Packing'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PREPARING', max_length=30)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_date', models.CharField(default='Tomorrow', max_length=50)),
                ('delivery_slot', models.CharField(default='05:30 AM - 07:00 AM', max_length=50)),
                ('delivery_address', models.TextField(default='Doorstep Delivery Location')),
                ('delivery_latitude', models.DecimalField(decimal_places=8, default=17.4319, max_digits=11)),
                ('delivery_longitude', models.DecimalField(decimal_places=8, default=78.4073, max_digits=11)),
                ('delivery_otp', models.CharField(default='4892', max_length=10)),
                ('payment_status', models.CharField(default='PAID (Prepaid Wallet)', max_length=50)),
                ('proof_image_url', models.URLField(blank=True, default='')),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_orders', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL)),
                ('hub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_orders', to='deliveries.locationhub')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='deliverytask',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='subscriptions.subscription'),
        ),
        migrations.CreateModel(
            name='LiveOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='deliveries.liveorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='deliveries.liveorder'),
        ),
    ]
