# Generated by Django 4.2.30 on 2026-08-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0006_liveorder_alter_deliverytask_subscription_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='deliverytask',
            index=models.Index(fields=['delivery_date', 'status'], name='deliv_date_status_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverytask',
            index=models.Index(fields=['driver', 'delivery_date'], name='deliv_driver_date_idx'),
        ),
        migrations.AddIndex(
            model_name='liveorder',
            index=models.Index(fields=['customer', '-created_at'], name='order_cust_created_idx'),
        ),
        migrations.AddIndex(
            model_name='liveorder',
            index=models.Index(fields=['status', '-created_at'], name='order_status_created_idx'),
        ),
    ]
