# Generated by Django 4.2.30 on 2026-08-20 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0008_bottle_return_and_provider_payout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveorder',
            name='delivery_address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='liveorder',
            name='delivery_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='liveorder',
            name='delivery_latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='liveorder',
            name='delivery_longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='liveorder',
            name='delivery_otp',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='liveorder',
            name='payment_status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
    ]
