# Generated by Django 4.2.30 on 2026-08-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0009_liveorder_delivery_date_to_datefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationhub',
            name='latitude',
            field=models.FloatField(default=17.001734),
        ),
        migrations.AlterField(
            model_name='locationhub',
            name='longitude',
            field=models.FloatField(default=79.9625),
        ),
    ]
