# Generated by Django 4.2.30 on 2026-08-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0010_alter_locationhub_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationhub',
            name='bank_account_holder',
            field=models.CharField(default='Srinuvasa Reddy', max_length=150),
        ),
        migrations.AddField(
            model_name='locationhub',
            name='bank_account_number',
            field=models.CharField(default='389201948210', max_length=50),
        ),
        migrations.AddField(
            model_name='locationhub',
            name='bank_ifsc',
            field=models.CharField(default='SBIN0004892', max_length=20),
        ),
        migrations.AddField(
            model_name='locationhub',
            name='bank_name',
            field=models.CharField(default='State Bank of India', max_length=150),
        ),
        migrations.AddField(
            model_name='locationhub',
            name='upi_id',
            field=models.CharField(default='8885199878@upi', max_length=100),
        ),
        migrations.AlterField(
            model_name='locationhub',
            name='coverage_radius_km',
            field=models.FloatField(default=8.5),
        ),
    ]
