# Generated by Django 4.2.30 on 2026-08-21 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0011_locationhub_bank_account_holder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('label', models.CharField(default='Morning', max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_orders', models.PositiveIntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
                ('cutoff_minutes_before', models.IntegerField(default=30)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_slots', to='deliveries.locationhub')),
            ],
            options={
                'ordering': ['start_time'],
                'unique_together': {('hub', 'name')},
            },
        ),
    ]
