# Generated by Django 4.2.30 on 2026-08-22 18:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deliveries', '0012_deliveryslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMilkBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=50, unique=True)),
                ('product_name', models.CharField(default='Pure Buffalo Milk', max_length=150)),
                ('batch_date', models.DateField(default=datetime.date.today)),
                ('fat_percentage', models.DecimalField(decimal_places=2, default=6.8, max_digits=4)),
                ('snf_percentage', models.DecimalField(decimal_places=2, default=9.0, max_digits=4)),
                ('water_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('price_per_litre', models.DecimalField(decimal_places=2, default=68.0, max_digits=8)),
                ('total_litres', models.DecimalField(decimal_places=2, default=450.0, max_digits=8)),
                ('temperature_celsius', models.DecimalField(decimal_places=1, default=3.8, max_digits=4)),
                ('status', models.CharField(choices=[('TESTED', 'Lab Tested & Verified'), ('DISPATCHED', 'Dispatched to Drivers'), ('COMPLETED', 'Fully Delivered')], default='DISPATCHED', max_length=20)),
                ('quality_certificate_note', models.CharField(blank=True, default='FSSAI Certified • Passed 24 Purity Checks', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispatched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_batches', to=settings.AUTH_USER_MODEL)),
                ('hub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_batches', to='deliveries.locationhub')),
            ],
            options={
                'ordering': ['-batch_date', '-created_at'],
                'indexes': [models.Index(fields=['batch_date', 'product_name'], name='batch_date_prod_idx')],
            },
        ),
    ]
