# Generated by Django 4.2.30 on 2026-08-22 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0013_dailymilkbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_tasks', to='deliveries.dailymilkbatch'),
        ),
        migrations.AddField(
            model_name='liveorder',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_orders', to='deliveries.dailymilkbatch'),
        ),
    ]
