# Generated by Django 4.2.30 on 2026-08-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0014_deliverytask_batch_liveorder_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveorder',
            name='delivery_latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='liveorder',
            name='delivery_longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True),
        ),
    ]
