# Generated by Django 4.2.30 on 2026-08-24 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_alter_subscription_delivery_latitude_and_more'),
        ('deliveries', '0015_alter_liveorder_delivery_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytask',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='deliveries.liveorder'),
        ),
        migrations.AlterField(
            model_name='deliverytask',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='subscriptions.subscription'),
        ),
    ]
