# Generated by Django 4.2.30 on 2026-08-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0016_alter_deliverytask_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='failure_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='deliverytask',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Scheduled (Pending)'), ('DELIVERED', 'Delivered at Doorstep'), ('SKIPPED', 'Skipped / Paused'), ('FAILED', 'FAILED')], default='PENDING', max_length=20),
        ),
    ]
