# Generated by Django 4.2.30 on 2026-08-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0017_deliverytask_failure_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveorder',
            name='delivery_type',
            field=models.CharField(choices=[('INSTANT', 'Instant Delivery'), ('SCHEDULED', 'Scheduled Delivery')], default='SCHEDULED', max_length=20),
        ),
        migrations.AddField(
            model_name='liveorder',
            name='estimated_delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liveorder',
            name='eta_minutes',
            field=models.IntegerField(default=0, help_text='Estimated delivery time in minutes'),
        ),
    ]
