# Generated by Django 4.2.30 on 2026-08-25 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_driving_license_user_vehicle_number'),
        ('deliveries', '0018_liveorder_delivery_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_tasks', to='accounts.customeraddress'),
        ),
        migrations.AddField(
            model_name='liveorder',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_orders', to='accounts.customeraddress'),
        ),
    ]
