from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0019_deliverytask_address_liveorder_address'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='DeliveryChatMessage',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('channel_key', models.CharField(db_index=True, max_length=100)),
                        ('sender_role', models.CharField(choices=[('DRIVER', 'Delivery Driver'), ('CUSTOMER', 'Customer'), ('SYSTEM', 'System Update')], default='DRIVER', max_length=20)),
                        ('sender_name', models.CharField(default='', max_length=150)),
                        ('sender_phone', models.CharField(blank=True, default='', max_length=30)),
                        ('text', models.TextField()),
                        ('is_read', models.BooleanField(default=False)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='deliveries.liveorder')),
                        ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='deliveries.deliverytask')),
                    ],
                    options={
                        'ordering': ['created_at'],
                        'indexes': [models.Index(fields=['channel_key', 'created_at'], name='deliv_chat_chan_idx')],
                    },
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    CREATE TABLE IF NOT EXISTS deliveries_deliverychatmessage (
                        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        channel_key varchar(100) NOT NULL,
                        sender_role varchar(20) NOT NULL DEFAULT 'DRIVER',
                        sender_name varchar(150) NOT NULL DEFAULT '',
                        sender_phone varchar(30) NOT NULL DEFAULT '',
                        text text NOT NULL,
                        is_read boolean NOT NULL DEFAULT false,
                        created_at timestamptz NOT NULL DEFAULT now(),
                        order_id bigint REFERENCES deliveries_liveorder(id) ON DELETE SET NULL,
                        task_id bigint REFERENCES deliveries_deliverytask(id) ON DELETE SET NULL
                    );
                    CREATE INDEX IF NOT EXISTS deliv_chat_chan_idx ON deliveries_deliverychatmessage (channel_key, created_at);
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                )
            ]
        ),
    ]
