from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deliveries', '0020_deliverychatmessage'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='CoverageExpansionRequest',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('phone', models.CharField(blank=True, default='', max_length=20)),
                        ('city', models.CharField(default='Kodad', max_length=100)),
                        ('area_name', models.CharField(blank=True, default='', max_length=255)),
                        ('latitude', models.FloatField(blank=True, null=True)),
                        ('longitude', models.FloatField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coverage_expansion_requests', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'ordering': ['-created_at'],
                    },
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    CREATE TABLE IF NOT EXISTS deliveries_coverageexpansionrequest (
                        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        phone varchar(20) NOT NULL DEFAULT '',
                        city varchar(100) NOT NULL DEFAULT 'Kodad',
                        area_name varchar(255) NOT NULL DEFAULT '',
                        latitude double precision NULL,
                        longitude double precision NULL,
                        created_at timestamptz NOT NULL DEFAULT now(),
                        user_id bigint REFERENCES accounts_user(id) ON DELETE SET NULL
                    );
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                )
            ]
        ),
    ]
