# Generated by Django 4.2.30 on 2026-09-03 10:56

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0022_deliverytask_cash_amount_deliverytask_cash_collected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='payout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_tasks', to='deliveries.providerpayout'),
        ),
        migrations.AddField(
            model_name='providerpayout',
            name='bank_account_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='providerpayout',
            name='bank_ifsc',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='providerpayout',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='providerpayout',
            name='cash_collected',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cash collected in hand at doorstep (COD)', max_digits=12),
        ),
        migrations.AddField(
            model_name='providerpayout',
            name='prepaid_revenue',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Online / Wallet prepaid revenue', max_digits=12),
        ),
        migrations.AddField(
            model_name='providerpayout',
            name='upi_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
