# Generated by Django 4.2.30 on 2026-09-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0023_deliverytask_payout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationhub',
            name='bank_account_holder',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='locationhub',
            name='bank_account_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='locationhub',
            name='bank_ifsc',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='locationhub',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='locationhub',
            name='upi_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
