# Generated by Django 4.2.30 on 2026-09-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0024_alter_locationhub_bank_account_holder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveorderitem',
            name='pack_size',
            field=models.CharField(blank=True, default='1 Litre', max_length=50),
        ),
        migrations.AlterField(
            model_name='deliverytask',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Scheduled (Pending)'), ('PICKED_UP', 'Picked Up from Hub'), ('ON_THE_WAY', 'Out for Delivery / On the Way'), ('DELIVERED', 'Delivered at Doorstep'), ('SKIPPED', 'Skipped / Paused'), ('FAILED', 'FAILED')], default='PENDING', max_length=20),
        ),
    ]
