# Generated by Django 4.2.30 on 2026-09-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0025_liveorderitem_pack_size_alter_deliverytask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveorder',
            name='status',
            field=models.CharField(choices=[('PLACED', 'Order Placed'), ('PREPARING', 'Preparing / Packing'), ('PICKED_UP', 'Order Picked Up'), ('OUT_FOR_DELIVERY', 'Out for Delivery / On the Way'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PREPARING', max_length=30),
        ),
    ]
