# Generated by Django 4.2.30 on 2026-09-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0026_alter_liveorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='delivered_latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='delivered_longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='liveorder',
            name='delivered_latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='liveorder',
            name='delivered_longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True),
        ),
    ]
