# Generated by Django 4.2.30 on 2026-09-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0028_liveorder_delivery_fee_liveorder_platform_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytask',
            name='proof_image_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='liveorder',
            name='proof_image_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
