# Generated by Django 4.2.30 on 2026-08-18 14:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_delivery_slot_preference_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.DecimalField(decimal_places=8, default=Decimal('17.43190000'), max_digits=11),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.DecimalField(decimal_places=8, default=Decimal('78.40730000'), max_digits=11),
        ),
    ]
