# Generated by Django 4.2.30 on 2026-08-19 06:46

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0004_deliverytask_hub'),
        ('accounts', '0004_create_default_admin_and_demo_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_partners', to='deliveries.locationhub'),
        ),
        migrations.AddField(
            model_name='user',
            name='driver_status',
            field=models.CharField(default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_salary',
            field=models.DecimalField(decimal_places=2, default=Decimal('15000.00'), max_digits=10),
        ),
    ]
