# Generated by Django 4.2.30 on 2026-08-19 07:57

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_assigned_hub_user_driver_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('HOME', 'Home 🏠'), ('WORK', 'Work / Office 💼'), ('OTHER', 'Other Location 📍')], default='HOME', max_length=20)),
                ('custom_tag', models.CharField(blank=True, default='', help_text='e.g. Parents Villa, Vacation House', max_length=100)),
                ('flat_house_no', models.CharField(blank=True, default='', max_length=100)),
                ('floor', models.CharField(blank=True, default='', max_length=50)),
                ('building_name', models.CharField(blank=True, default='', max_length=150)),
                ('street_address', models.CharField(default='Road No. 36, Jubilee Hills', max_length=255)),
                ('landmark', models.CharField(blank=True, default='', max_length=150)),
                ('city', models.CharField(default='Hyderabad', max_length=100)),
                ('pincode', models.CharField(default='500033', max_length=20)),
                ('latitude', models.DecimalField(decimal_places=8, default=Decimal('17.43190000'), max_digits=11)),
                ('longitude', models.DecimalField(decimal_places=8, default=Decimal('78.40730000'), max_digits=11)),
                ('delivery_instructions', models.CharField(blank=True, default='Leave in doorstep milk basket, ring bell', max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Customer Addresses',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
