# Generated by Django 4.2.30 on 2026-08-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customeraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('DRIVER', 'Delivery Partner'), ('PROVIDER', 'Location Hub Owner / Provider'), ('ADMIN', 'Administrator')], default='CUSTOMER', max_length=20),
        ),
    ]
