# Generated by Django 4.2.30 on 2026-08-21 11:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_non_negative_wallet_balance_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='city',
            field=models.CharField(default='Kodad', max_length=100),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='latitude',
            field=models.DecimalField(decimal_places=8, default=Decimal('17.00173400'), max_digits=11),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='longitude',
            field=models.DecimalField(decimal_places=8, default=Decimal('79.96250000'), max_digits=11),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='pincode',
            field=models.CharField(default='508206', max_length=20),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='street_address',
            field=models.CharField(default='Main Road, Kodad', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(default='Kodad', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='latitude',
            field=models.DecimalField(decimal_places=8, default=Decimal('17.00173400'), max_digits=11),
        ),
        migrations.AlterField(
            model_name='user',
            name='longitude',
            field=models.DecimalField(decimal_places=8, default=Decimal('79.96250000'), max_digits=11),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('DRIVER', 'Delivery Partner'), ('PROVIDER', 'Location Hub Owner / Provider'), ('SUPPORT', 'Support Executive / Agent'), ('ADMIN', 'Administrator')], default='CUSTOMER', max_length=20),
        ),
    ]
