# Generated by Django 4.2.30 on 2026-08-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customeraddress_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_param',
            field=models.CharField(blank=True, default='', help_text='Target parameter like category key or ID', max_length=100),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_screen',
            field=models.CharField(blank=True, default='', help_text='Target screen code: DELIVERIES, WALLET, SUBSCRIPTIONS, CATEGORY, OFFERS, SUPPORT', max_length=50),
        ),
    ]
