# Generated by Django 4.2.30 on 2026-08-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_notification_target_param_notification_target_screen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_location_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
