# Generated by Django 4.2.30 on 2026-08-22 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_last_location_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('sender_type', models.CharField(choices=[('user', 'Customer'), ('agent', 'Support Agent'), ('system', 'System')], default='user', max_length=10)),
                ('sender_name', models.CharField(default='Customer', max_length=100)),
                ('text', models.TextField()),
                ('order_id', models.CharField(blank=True, max_length=50, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['phone', 'created_at'], name='supp_phone_created_idx')],
            },
        ),
    ]
