# Generated by Django 4.2.30 on 2026-08-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_supportmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='driving_license',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
