# Generated by Django 4.2.30 on 2026-08-25 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_driving_license_user_vehicle_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraddress',
            name='user',
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='customer',
            field=models.ForeignKey(db_column='customer_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='saved_addresses', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
