# Generated by Django 4.2.30 on 2026-08-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_customeraddress_user_customeraddress_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='street_address',
            field=models.CharField(blank=True, default='Main Road, Kodad', max_length=255),
        ),
    ]
