# Generated by Django 4.2.30 on 2026-08-25 12:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_customeraddress_street_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='latitude',
            field=models.DecimalField(decimal_places=10, default=Decimal('17.00173400'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='longitude',
            field=models.DecimalField(decimal_places=10, default=Decimal('79.96250000'), max_digits=18),
        ),
    ]
