# Generated by Django 4.2.30 on 2026-08-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_customeraddress_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male 👨'), ('Female', 'Female 👩'), ('Other', 'Other 👤')], default='Male', max_length=10),
        ),
    ]
