from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_user_gender'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='DeviceToken',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('token', models.CharField(db_index=True, max_length=512, unique=True)),
                        ('platform', models.CharField(choices=[('IOS', 'iOS'), ('ANDROID', 'Android'), ('WEB', 'Web')], default='IOS', max_length=10)),
                        ('device_name', models.CharField(blank=True, default='', max_length=150)),
                        ('is_active', models.BooleanField(db_index=True, default=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'ordering': ['-updated_at'],
                        'indexes': [models.Index(fields=['user', 'is_active'], name='devtok_user_active_idx')],
                    },
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    CREATE TABLE IF NOT EXISTS accounts_devicetoken (
                        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        token varchar(512) NOT NULL UNIQUE,
                        platform varchar(10) NOT NULL DEFAULT 'IOS',
                        device_name varchar(150) NOT NULL DEFAULT '',
                        is_active boolean NOT NULL DEFAULT true,
                        created_at timestamptz NOT NULL DEFAULT now(),
                        updated_at timestamptz NOT NULL DEFAULT now(),
                        user_id bigint NOT NULL REFERENCES accounts_user(id) ON DELETE CASCADE
                    );
                    CREATE INDEX IF NOT EXISTS devtok_user_active_idx ON accounts_devicetoken (user_id, is_active);
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                )
            ]
        ),
    ]
