# Generated by Django 4.2.30 on 2026-09-09 13:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_commission_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0500'), help_text='Platform commission rate (e.g. 0.05 = 5%)', max_digits=5)),
                ('default_milk_price_per_litre', models.DecimalField(decimal_places=2, default=Decimal('68.00'), help_text='Fallback milk price per litre when product price unavailable', max_digits=8)),
                ('max_wallet_topup', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), help_text='Maximum wallet top-up amount per transaction', max_digits=10)),
                ('welcome_bonus_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Welcome bonus credited to new user wallets (0 = disabled)', max_digits=8)),
                ('morning_cutoff_hour', models.IntegerField(default=5, help_text='Hour (0-23) after which morning tasks are generated')),
                ('morning_cutoff_minute', models.IntegerField(default=0, help_text='Minute (0-59) for morning cutoff')),
                ('afternoon_cutoff_hour', models.IntegerField(default=12, help_text='Hour (0-23) after which tasks are for next day')),
                ('default_delivery_slot', models.CharField(default='05:30 AM - 07:00 AM', help_text='Default delivery slot label', max_length=50)),
                ('max_hub_distance_km', models.FloatField(default=10.0, help_text='Maximum distance in km for hub assignment')),
                ('support_phone', models.CharField(default='+91 8919548905', max_length=20)),
                ('support_whatsapp', models.CharField(default='918919548905', max_length=20)),
                ('support_email', models.EmailField(default='support@pamba.in', max_length=254)),
                ('default_city', models.CharField(default='Kodad', max_length=50)),
                ('google_maps_api_key', models.CharField(blank=True, default='', help_text='Google Maps API key', max_length=100)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
