# Generated by Django 4.2.30 on 2026-09-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='ninzasms_api_key',
            field=models.CharField(default='NINZASMS06324354f5fed8b13a50be5fc7d20d3ef480963ea78c5b6cf0b6', help_text='NinzaSMS Authorization Key', max_length=150),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='ninzasms_enabled',
            field=models.BooleanField(default=True, help_text='Enable real SMS OTP delivery via NinzaSMS'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='ninzasms_sender_id',
            field=models.CharField(default='15809', help_text='NinzaSMS Approved Sender ID', max_length=50),
        ),
    ]
