# Generated by Django 4.2.30 on 2026-09-10 13:51

from decimal import Decimal
from django.db import migrations, models


def add_siteconfig_fees(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    with schema_editor.connection.cursor() as cursor:
        if vendor == 'postgresql':
            cursor.execute("""
                ALTER TABLE core_siteconfig ADD COLUMN IF NOT EXISTS customer_platform_fee numeric(6,2) DEFAULT 0.00;
                ALTER TABLE core_siteconfig ADD COLUMN IF NOT EXISTS delivery_fee numeric(6,2) DEFAULT 0.00;
                ALTER TABLE core_siteconfig ADD COLUMN IF NOT EXISTS free_delivery_threshold numeric(8,2) DEFAULT 0.00;
                ALTER TABLE core_siteconfig ADD COLUMN IF NOT EXISTS tax_percentage numeric(5,2) DEFAULT 0.00;
            """)
        else:
            cursor.execute("PRAGMA table_info(core_siteconfig)")
            cols = {row[1] for row in cursor.fetchall()}
            if "customer_platform_fee" not in cols:
                cursor.execute("ALTER TABLE core_siteconfig ADD COLUMN customer_platform_fee decimal DEFAULT 0.00")
            if "delivery_fee" not in cols:
                cursor.execute("ALTER TABLE core_siteconfig ADD COLUMN delivery_fee decimal DEFAULT 0.00")
            if "free_delivery_threshold" not in cols:
                cursor.execute("ALTER TABLE core_siteconfig ADD COLUMN free_delivery_threshold decimal DEFAULT 0.00")
            if "tax_percentage" not in cols:
                cursor.execute("ALTER TABLE core_siteconfig ADD COLUMN tax_percentage decimal DEFAULT 0.00")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_siteconfig_ninzasms_api_key_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='siteconfig',
                    name='customer_platform_fee',
                    field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Customer platform fee in Rupees per order (0.00 for none/free)', max_digits=6),
                ),
                migrations.AddField(
                    model_name='siteconfig',
                    name='delivery_fee',
                    field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Standard delivery partner fee in Rupees (0.00 for free delivery)', max_digits=6),
                ),
                migrations.AddField(
                    model_name='siteconfig',
                    name='free_delivery_threshold',
                    field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum order subtotal for free delivery', max_digits=8),
                ),
                migrations.AddField(
                    model_name='siteconfig',
                    name='tax_percentage',
                    field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax / GST percentage applied to checkout orders', max_digits=5),
                ),
                migrations.AlterField(
                    model_name='siteconfig',
                    name='ninzasms_api_key',
                    field=models.CharField(default='', help_text='NinzaSMS Authorization Key', max_length=150),
                ),
                migrations.AlterField(
                    model_name='siteconfig',
                    name='ninzasms_sender_id',
                    field=models.CharField(default='', help_text='NinzaSMS Approved Sender ID', max_length=50),
                ),
            ],
            database_operations=[
                migrations.RunPython(add_siteconfig_fees, reverse_code=migrations.RunPython.noop)
            ]
        )
    ]
