# Generated by Django 4.2.30 on 2026-09-10 13:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_siteconfig_ninzasms_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='customer_platform_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Customer platform fee in Rupees per order (0.00 for none/free)', max_digits=6),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Standard delivery partner fee in Rupees (0.00 for free delivery)', max_digits=6),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='free_delivery_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum order subtotal for free delivery', max_digits=8),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax / GST percentage applied to checkout orders', max_digits=5),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='ninzasms_api_key',
            field=models.CharField(default='', help_text='NinzaSMS Authorization Key', max_length=150),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='ninzasms_sender_id',
            field=models.CharField(default='', help_text='NinzaSMS Approved Sender ID', max_length=50),
        ),
    ]
