# Generated by Django 4.2.30 on 2026-08-18 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('schedule_type', models.CharField(choices=[('DAILY', 'Everyday (Daily)'), ('ALTERNATE', 'Alternate Days'), ('CUSTOM', 'Custom Days'), ('ONCE', 'One Time Order')], default='DAILY', max_length=20)),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Vacation / Paused'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='VacationPause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(blank=True, default='Out of town', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_pauses', to='subscriptions.subscription')),
            ],
        ),
    ]
