# Generated by Django 4.2.30 on 2026-08-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscription_hub'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='delivery_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='subscription',
            name='delivery_instructions',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='delivery_latitude',
            field=models.DecimalField(decimal_places=8, default=17.4319, max_digits=11),
        ),
        migrations.AddField(
            model_name='subscription',
            name='delivery_longitude',
            field=models.DecimalField(decimal_places=8, default=78.4073, max_digits=11),
        ),
        migrations.AddField(
            model_name='subscription',
            name='delivery_slot',
            field=models.CharField(default='05:30 AM - 07:00 AM', max_length=50),
        ),
        migrations.AddField(
            model_name='subscription',
            name='pack_size',
            field=models.CharField(blank=True, default='1 Litre', max_length=50),
        ),
    ]
