# Generated by Django 4.2.30 on 2026-08-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscription_delivery_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='delivery_latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='delivery_longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
    ]
