# Generated by Django 4.2.30 on 2026-08-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_make_subscription_coords_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='effective_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
