# Generated by Django 4.2.30 on 2026-08-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_subscription_effective_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='delivery_latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='delivery_longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True),
        ),
    ]
