# Generated by Django 4.2.30 on 2026-08-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_alter_subscription_delivery_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='schedule_type',
            field=models.CharField(choices=[('DAILY', 'Everyday (Daily)'), ('ALTERNATE', 'Alternate Days'), ('CUSTOM', 'Custom Days'), ('ONCE', 'One Time Order'), ('WEEKDAYS', 'Weekdays Only')], default='DAILY', max_length=20),
        ),
    ]
