# Generated by Django 4.2.30 on 2026-08-25 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_driving_license_user_vehicle_number'),
        ('subscriptions', '0008_clear_all_subscriptions_fresh_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='accounts.customeraddress'),
        ),
    ]
