# Generated by Django 4.2.30 on 2026-09-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_subscription_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='custom_days',
            field=models.CharField(blank=True, default='0,2,4', help_text='Comma-separated weekday numbers (0=Mon, 1=Tue, 2=Wed, 3=Thu, 4=Fri, 5=Sat, 6=Sun) for CUSTOM schedule', max_length=50),
        ),
    ]
