# Generated by Django 4.2.30 on 2026-09-10 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_subscription_custom_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
