# Generated by Django 4.2.30 on 2026-08-18 11:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=Decimal('35.00'), max_digits=8)),
                ('unit', models.CharField(choices=[('LITER', 'Liter (L)'), ('ML', 'Milliliter (mL)'), ('PACKET', 'Pouch / Pack'), ('GRAM', 'Gram (g)'), ('KG', 'Kilogram (kg)')], default='LITER', max_length=20)),
                ('unit_quantity', models.CharField(default='500 mL', max_length=50)),
                ('image_url', models.URLField(blank=True, default='')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
