# Generated by Django 4.2.30 on 2026-08-18 12:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='badge_text',
            field=models.CharField(blank=True, default='Bestseller', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MILK', 'Pure Milk'), ('CURD_PANEER', 'Curd & Paneer'), ('GHEE_BUTTER', 'Desi Ghee & Butter'), ('SPECIALS', 'Organic Specials')], default='MILK', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='farm_origin',
            field=models.CharField(blank=True, default='Heritage Farm, Shamirpet', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='nutrition_info',
            field=models.CharField(blank=True, default='3.5% Fat | 8.5% SNF | Zero Additives', max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=Decimal('4.9'), max_digits=3),
        ),
    ]
