# Generated by Django 4.2.30 on 2026-08-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_badge_text_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MILK', 'Milk'), ('MEAT', 'Meat'), ('EGGS', 'Eggs'), ('WATER_CAN', 'Water Can')], default='MILK', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='farm_origin',
            field=models.CharField(blank=True, default='Heritage Source, Hyderabad', max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='nutrition_info',
            field=models.CharField(blank=True, default='100% Pure & Certified Quality', max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('LITER', 'Liter (L)'), ('ML', 'Milliliter (mL)'), ('PACKET', 'Pouch / Pack'), ('GRAM', 'Gram (g)'), ('KG', 'Kilogram (kg)'), ('PCS', 'Pieces / Count'), ('CAN', 'Water Can')], default='LITER', max_length=20),
        ),
    ]
