# Generated by Django 4.2.30 on 2026-08-20 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0009_liveorder_delivery_date_to_datefield'),
        ('products', '0005_category_alter_product_category_product_category_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubProductInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_capacity_slots', models.PositiveIntegerField(default=100, help_text='Total daily available capacity slots (e.g. 100 Litres/Units)')),
                ('booked_slots', models.PositiveIntegerField(default=0, help_text='Currently booked slots for today')),
                ('is_available', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='deliveries.locationhub')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hub_inventories', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Hub Product Inventories',
                'unique_together': {('hub', 'product')},
            },
        ),
    ]
