# Generated by Django 4.2.30 on 2026-08-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_hubproductinventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorefrontConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image_url', models.URLField(blank=True, default='https://images.unsplash.com/photo-1527153857715-3908f2bae5e8?auto=format&fit=crop&w=1200&q=80', help_text='Direct URL or CDN/S3 URL for top banner image', max_length=500)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='storefront_banners/')),
                ('headline', models.CharField(default='Order by 11PM Tonight →', max_length=200)),
                ('subtitle', models.CharField(default='❄️ 4°C Cold Chain • Farm to Doorstep • Kodad Hub', max_length=300)),
                ('dispatch_tag', models.CharField(default='MORNING DROP 05:30 AM ☀️', max_length=100)),
                ('promo_chip', models.CharField(default='🥛 FRESH TODAY', max_length=100)),
                ('cta_text', models.CharField(default='SUBSCRIBE NOW ➔', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Storefront Configuration',
                'verbose_name_plural': 'Storefront Configurations',
            },
        ),
    ]
