# Generated by Django 4.2.30 on 2026-08-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_storefrontconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
