# Generated by Django 4.2.30 on 2026-09-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_category_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storefrontconfig',
            name='cta_text',
            field=models.CharField(blank=True, default='SUBSCRIBE NOW ➔', max_length=100),
        ),
        migrations.AlterField(
            model_name='storefrontconfig',
            name='dispatch_tag',
            field=models.CharField(blank=True, default='MORNING DROP 05:30 AM ☀️', max_length=100),
        ),
        migrations.AlterField(
            model_name='storefrontconfig',
            name='headline',
            field=models.CharField(blank=True, default='Order by 11PM Tonight →', max_length=200),
        ),
        migrations.AlterField(
            model_name='storefrontconfig',
            name='promo_chip',
            field=models.CharField(blank=True, default='🥛 FRESH TODAY', max_length=100),
        ),
        migrations.AlterField(
            model_name='storefrontconfig',
            name='subtitle',
            field=models.CharField(blank=True, default='❄️ 4°C Cold Chain • Farm to Doorstep • Kodad Hub', max_length=300),
        ),
    ]
