# Generated by Django 4.2.30 on 2026-09-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_storefrontconfig_cta_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='quality_badge_title',
            field=models.CharField(blank=True, default='', help_text='Purity badge header (e.g. FSSAI Certified • 100% Antibiotic-Free)', max_length=150),
        ),
        migrations.AddField(
            model_name='category',
            name='quality_specs',
            field=models.JSONField(blank=True, default=dict, help_text='Quality specifications key-values shown in expandable card'),
        ),
        migrations.AddField(
            model_name='category',
            name='subtitle',
            field=models.CharField(blank=True, default='', help_text='Subtitle displayed in mobile app (e.g. Fresh & Tender • 100% Antibiotic-Free)', max_length=150),
        ),
        migrations.AddField(
            model_name='category',
            name='tracking_badges',
            field=models.JSONField(blank=True, default=list, help_text='Tracking status badges shown on live driver tracking screen'),
        ),
        migrations.AddField(
            model_name='product',
            name='quality_badge_title',
            field=models.CharField(blank=True, default='', help_text='Product-specific badge title override (falls back to category badge if blank)', max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='quality_specs',
            field=models.JSONField(blank=True, default=dict, help_text='Product-specific quality specs override (dict, falls back to category if empty)'),
        ),
        migrations.AddField(
            model_name='product',
            name='subtitle',
            field=models.CharField(blank=True, default='', help_text='Product-specific subtitle override (falls back to category subtitle if blank)', max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='tracking_badges',
            field=models.JSONField(blank=True, default=list, help_text='Product-specific tracking badges override (list of dicts, falls back to category if empty)'),
        ),
    ]
