# Generated by Django 4.2.30 on 2026-09-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_category_quality_badge_title_category_quality_specs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storefrontconfig',
            name='is_cod_enabled',
            field=models.BooleanField(default=True, help_text='Allow customers to select Cash on Delivery (COD) / Doorstep UPI'),
        ),
        migrations.AddField(
            model_name='storefrontconfig',
            name='is_wallet_enabled',
            field=models.BooleanField(default=True, help_text='Allow customers to pay using prepaid Pamba Wallet'),
        ),
    ]
