# Generated by Django 4.2.30 on 2026-09-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_storefrontconfig_is_cod_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storefrontconfig',
            name='is_online_payment_enabled',
            field=models.BooleanField(default=True, help_text='Allow customers to pay online via Razorpay (UPI, Cards, NetBanking)'),
        ),
    ]
