# Generated by Django 4.2.30 on 2026-09-10 13:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_storefrontconfig_is_online_payment_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='storefrontconfig',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Standard delivery partner fee in Rupees (0.00 for free delivery)', max_digits=6),
        ),
        migrations.AddField(
            model_name='storefrontconfig',
            name='free_delivery_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum order subtotal in Rupees for free delivery (0.00 to disable)', max_digits=8),
        ),
        migrations.AddField(
            model_name='storefrontconfig',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Customer platform fee in Rupees per order (0.00 for none/free)', max_digits=6),
        ),
        migrations.AddField(
            model_name='storefrontconfig',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax / GST percentage applied to items (e.g. 5.00 for 5%)', max_digits=5),
        ),
    ]
