# Generated by Django 4.2.30 on 2026-09-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_storefrontconfig_delivery_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='banner_en',
            field=models.CharField(blank=True, default='', help_text='Hero banner text in English', max_length=200),
        ),
        migrations.AddField(
            model_name='category',
            name='banner_te',
            field=models.CharField(blank=True, default='', help_text='Hero banner text in Telugu', max_length=200),
        ),
        migrations.AddField(
            model_name='category',
            name='gradient_colors',
            field=models.JSONField(blank=True, default=list, help_text="Hero banner gradient stops, e.g. ['#0369A1', '#0284C7']"),
        ),
        migrations.AddField(
            model_name='category',
            name='name_te',
            field=models.CharField(blank=True, default='', help_text='Telugu category name (e.g. పాలు & డైరీ)', max_length=150),
        ),
        migrations.AddField(
            model_name='category',
            name='subtags',
            field=models.JSONField(blank=True, default=list, help_text="Quick filter tags list (e.g. ['ALL', 'COW MILK', 'BUFFALO'])"),
        ),
        migrations.AddField(
            model_name='category',
            name='subtitle_te',
            field=models.CharField(blank=True, default='', help_text='Telugu category subtitle', max_length=200),
        ),
        migrations.AddField(
            model_name='category',
            name='tile_bg_color',
            field=models.CharField(blank=True, default='#E6F5F0', help_text='Tile background hex color', max_length=20),
        ),
        migrations.AddField(
            model_name='category',
            name='tile_fg_color',
            field=models.CharField(blank=True, default='#0D7C66', help_text='Tile foreground accent hex color', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='badge_text_te',
            field=models.CharField(blank=True, default='', help_text='Telugu badge text', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='description_te',
            field=models.TextField(blank=True, default='', help_text='Product description in Telugu'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_subscription_enabled',
            field=models.BooleanField(default=True, help_text='Whether recurring subscriptions can be created for this product'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_te',
            field=models.CharField(blank=True, default='', help_text='Product name in Telugu', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='pack_sizes',
            field=models.JSONField(blank=True, default=list, help_text="Explicit pack sizes and prices: [{'size': '500 ml', 'price': 39.0}]"),
        ),
        migrations.AddField(
            model_name='product',
            name='subtitle_te',
            field=models.CharField(blank=True, default='', help_text='Telugu subtitle override', max_length=200),
        ),
    ]
