import os
import django

if __name__ == "__main__":
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "milk_backend.settings")
    django.setup()

from apps.accounts.models import User


def auto_heal_schema():
    print("🛠️ [Railway DB Initializer] Ensuring schema consistency and token_blacklist tables...")
    from django.db import connection
    from django.core.management import call_command

    # 1. Ensure token_blacklist tables exist in Postgres
    try:
        with connection.cursor() as cursor:
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS token_blacklist_outstandingtoken (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    token text NOT NULL,
                    created_at timestamp with time zone,
                    expires_at timestamp with time zone NOT NULL,
                    user_id bigint,
                    jti varchar(255) NOT NULL UNIQUE
                );
                CREATE TABLE IF NOT EXISTS token_blacklist_blacklistedtoken (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    blacklisted_at timestamp with time zone NOT NULL,
                    token_id bigint NOT NULL UNIQUE
                );
                CREATE TABLE IF NOT EXISTS payments_razorpaypayment (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    purpose varchar(32) NOT NULL DEFAULT 'WALLET_TOPUP',
                    amount numeric(10, 2) NOT NULL DEFAULT 0.00,
                    currency varchar(10) NOT NULL DEFAULT 'INR',
                    razorpay_order_id varchar(128) NOT NULL UNIQUE,
                    razorpay_payment_id varchar(128),
                    razorpay_signature varchar(256),
                    status varchar(20) NOT NULL DEFAULT 'PENDING',
                    error_description text,
                    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
                    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    order_id varchar(64),
                    user_id bigint NOT NULL
                );
                CREATE INDEX IF NOT EXISTS payments_razorpaypayment_user_id_idx ON payments_razorpaypayment(user_id);
                CREATE INDEX IF NOT EXISTS payments_razorpaypayment_status_idx ON payments_razorpaypayment(status);
            """)
        print("✅ [Railway DB Initializer] Direct token_blacklist & payments DDL verified.")
    except Exception as ddl_err:
        print("⚠️ [Railway DB Initializer] DDL fallback notice:", ddl_err)

    # 2. Run app-by-app migrations
    apps_to_migrate = [
        "contenttypes", "auth", "accounts", "admin", "sessions",
        "token_blacklist", "products", "deliveries", "subscriptions", "payments"
    ]
    for app in apps_to_migrate:
        try:
            call_command('migrate', app, interactive=False)
        except Exception as app_mig_err:
            print(f"⚠️ Migration note for {app}:", app_mig_err)

    try:
        call_command('migrate', interactive=False)
        print("✅ [Railway DB Initializer] All migrations caught up successfully.")
    except Exception as mig_err:
        print("⚠️ [Railway DB Initializer] Migration catch-up notice:", mig_err)


def seed():
    auto_heal_schema()
    print("🌱 [Railway DB Initializer] Ensuring Super Admin account exists...")

    # 1. Permanent Super Admin Account (zero hardcoded categories, products, hubs, or banners)
    admin, created = User.objects.get_or_create(
        username="admin",
        defaults={
            "phone": "+91 8919548905",
            "email": "admin@milkdrop.in",
            "first_name": "Operations",
            "last_name": "Administrator",
            "role": User.Roles.ADMIN,
            "is_staff": True,
            "is_superuser": True,
            "city": "Kodad",
            "address": "Operations Command Center",
            "latitude": 17.001734,
            "longitude": 79.962500,
        },
    )
    if created:
        admin.set_password("admin123")
        admin.save()
        print("🛡️ [Super Admin Initialized]: admin / admin123 (Phone: +91 8919548905)")
    else:
        admin.role = User.Roles.ADMIN
        admin.is_staff = True
        admin.is_superuser = True
        admin.save()

    # 1b. Ensure 7794893990 is configured as a standard Customer account
    customer_user = User.objects.filter(phone__endswith="7794893990").first()
    if customer_user:
        customer_user.role = User.Roles.CUSTOMER
        customer_user.is_staff = False
        customer_user.is_superuser = False
        customer_user.save()
        print("👤 [Customer Role Updated]: Manideep Reddy (+91 7794893990) -> CUSTOMER")

    # 2. Ensure active categories exist and have rich presentation metadata
    try:
        from apps.products.models import Category
        core_categories = [
            {
                "name": "Fresh Milk",
                "slug": "milk",
                "icon": "🥛",
                "subtitle": "⚡ Milked at 3 AM • Delivered by 6 AM",
                "quality_badge_title": "100% PURE & CERTIFIED QUALITY",
                "description": "Farm Fresh A2 Desi Cow and Buffalo Milk in glass bottles and pouches",
                "display_order": 1,
            },
            {
                "name": "Farm Eggs",
                "slug": "eggs",
                "icon": "🥚",
                "subtitle": "Daily Dawn Harvested • Free-Range & Organic",
                "quality_badge_title": "100% ANTIBIOTIC-FREE EGGS",
                "description": "Free-Range Country Brown and Farm Graded table eggs",
                "display_order": 2,
            },
            {
                "name": "Water Cans",
                "slug": "water-can",
                "icon": "💧",
                "subtitle": "8-Stage RO + UV Purified • Daily Sanitized",
                "quality_badge_title": "100% FOOD-GRADE MINERAL WATER",
                "description": "20L RO Purified & UV Treated Mineral Drinking Water Cans",
                "display_order": 3,
            },
            {
                "name": "Fresh Dairy",
                "slug": "dairy",
                "icon": "🧈",
                "subtitle": "Traditional Bilona Churned • 100% Pure Vedic",
                "quality_badge_title": "ARTISANAL FARM DAIRY",
                "description": "Artisanal Bilona Desi Ghee & Fresh White Butter",
                "display_order": 4,
            },
        ]
        for cat_data in core_categories:
            cat = Category.objects.filter(slug=cat_data["slug"]).first()
            if not cat:
                cat = Category.objects.filter(name__iexact=cat_data["name"]).first()
            if cat:
                for k, v in cat_data.items():
                    setattr(cat, k, v)
                cat.save()
            else:
                Category.objects.create(**cat_data)
        print(f"📦 [Railway DB Initializer] Core categories ensured with rich backend metadata.")
    except Exception as e:
        print("Category seeding notice:", e)

    # 2b. Ensure valid CDN image URLs for products
    try:
        from apps.products.models import Product
        ghee_prod = Product.objects.filter(name__icontains="Ghee").first()
        if ghee_prod and ("photo-1589927986076" in (ghee_prod.image_url or "") or not ghee_prod.image_url):
            ghee_prod.image_url = "https://images.unsplash.com/photo-1628088062854-d1870b4553da?auto=format&fit=crop&w=800&q=80"
            ghee_prod.save()

        water_prod = Product.objects.filter(name__icontains="Bisleri").first()
        if water_prod and ("photo-1548839140" in (water_prod.image_url or "") or not water_prod.image_url):
            water_prod.image_url = "https://images.unsplash.com/photo-1523362628745-0c100150b504?auto=format&fit=crop&w=800&q=80"
            water_prod.save()
    except Exception as e:
        print("Product image URL fix notice:", e)

    # 3. Ensure Hub Coverage & Service Areas
    try:
        from apps.deliveries.models import LocationHub, ServiceArea
        from apps.products.models import Product, HubProductInventory
        from django.db.models import Q

        # Ensure coordinates are set without overwriting administrator-configured coverage radius
        mlc_hub = LocationHub.objects.filter(Q(hub_code="HUB-MLC-01") | Q(name__icontains="Mella Chervu")).first()
        if mlc_hub:
            changed = False
            if not mlc_hub.latitude or not mlc_hub.longitude:
                mlc_hub.latitude = 16.817715
                mlc_hub.longitude = 79.933978
                changed = True
            if not mlc_hub.coverage_radius_km:
                mlc_hub.coverage_radius_km = 8.5
                changed = True
            if changed:
                mlc_hub.save()

        kdd_hub = LocationHub.objects.filter(Q(hub_code="HUB-KDD-01") | Q(name__icontains="Kodad")).first()
        if kdd_hub and not kdd_hub.coverage_radius_km:
            kdd_hub.coverage_radius_km = 8.5
            kdd_hub.save()

        # Seed Service Areas
        if mlc_hub:
            ServiceArea.objects.get_or_create(
                name="Mellacheruvu",
                defaults={
                    "pincodes": "508246",
                    "hub": mlc_hub,
                    "radius_km": 15.0,
                    "status": ServiceArea.Statuses.ACTIVE,
                    "popular_societies": "Mellacheruvu Town, Main Road, Temple Road",
                },
            )

        if kdd_hub:
            ServiceArea.objects.get_or_create(
                name="Kodad",
                defaults={
                    "pincodes": "508206",
                    "hub": kdd_hub,
                    "radius_km": 15.0,
                    "status": ServiceArea.Statuses.ACTIVE,
                    "popular_societies": "RTC Bus Depot Colony, Main Road, Gandhi Nagar",
                },
            )

        # Ensure Hub Inventory for all active hubs
        all_products = list(Product.objects.all())
        for hub in LocationHub.objects.all():
            for p in all_products:
                HubProductInventory.objects.get_or_create(
                    hub=hub,
                    product=p,
                    defaults={
                        "daily_capacity_slots": 100,
                        "booked_slots": 0,
                        "is_available": True,
                    },
                )
        print("🛒 [Railway DB Initializer] Hub product inventories ensured across all hubs.")
    except Exception as e:
        print("Hub and inventory initialization notice:", e)

    # 4. Auto-generate / reconcile today's delivery tasks for all active subscriptions (Same-Day only at 12:00 AM)
    try:
        from apps.deliveries.models import DeliveryTask
        from apps.deliveries.task_generator import generate_daily_tasks_for_date
        from datetime import date
        # Purge any prematurely generated future tasks
        purged = DeliveryTask.objects.filter(delivery_date__gt=date.today(), status=DeliveryTask.Statuses.PENDING).delete()
        if purged[0] > 0:
            print(f"🧹 [Railway DB Initializer] Cleaned up {purged[0]} prematurely generated future tasks.")
        today_res = generate_daily_tasks_for_date(target_date=date.today(), force=True)
        print(f"📦 [Railway DB Initializer] Delivery tasks active: Today ({today_res.get('created', 0)} new).")
    except Exception as task_err:
        print("Delivery task initialization notice:", task_err)

    print("✅ [Railway DB Initializer] Ready with dynamic backend architecture.")


if __name__ == "__main__":
    seed()
